CREATE TABLE TABLE_CUSTOMER (ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(40),
LAST_NAME VARCHAR(40),
CREATE_DATE TIMESTAMP ,
UPDATE_DATE TIMESTAMP );

INSERT INTO TABLE_CUSTOMER VALUES (100, 'SHUB', 'SINGH', SYSDATE, SYSDATE);
INSERT INTO TABLE_CUSTOMER VALUES (101, 'SHUBI', 'PINGH', SYSDATE, SYSDATE);